import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/Avatar.png";
import design from "../public/design.png";
import { motion } from "framer-motion";
import Text from "./Text";
import Skills from "./skills";
import SkillsImages from "./skillsImages";

export default function Home() {
  return (
    <div className="scrollbar scrollbar-track-orange-500/20 scrollbar-thumb-orange-500/80">
      <Head>
        <title>Harshith Mente</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10">
        <section className="min-h-screen">
          <nav className="py-4 mb-12 flex justify-end">
            <nav className=" px-2 sm:px-4  dark:bg  w-full  top-0 left-0 ">
              <div className="container flex flex-wrap items-center justify-between mx-auto">
                <a href="" className="flex items-center">
                  <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">
                    Yayyy!
                  </span>
                </a>
                <div className="flex md:order-2">
                  <button
                    type="button"
                    className=" font-medium rounded-lg text-lg px-5 py-2.5 text-center md:mr-0 dark:bg-orange-500"
                  >
                    Resume
                  </button>
                </div>
                <div
                  className="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
                  id="navbar-sticky"
                >
                  <ul className="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0  dark:border-gray-700">
                    <li>
                      <a
                        href="#Home"
                        className="block py-2 pl-3 pr-4 text-white  rounded md:bg-transparent md:p-0 dark:text-white"
                        aria-current="page"
                      >
                        Home
                      </a>
                    </li>
                    <li>
                      <a
                        href="#project"
                        className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                      >
                        Projects
                      </a>
                    </li>
                    <li>
                      <a
                        href="#skills"
                        className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent  md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                      >
                        Skills
                      </a>
                    </li>
                    <li>
                      <a
                        href="#Education"
                        className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                      >
                        Education
                      </a>
                    </li>
                    <li>
                      <a
                        href="#Achievements"
                        className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                      >
                        Achievements
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

            {/*           
         <a href="https://www.instagram.com/harshith.mente/">
         <div className='text-5xl px-6 flex transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-130 hover: duration-800'>
<AiFillInstagram/>
        </div>
       
         </a>
         <a href=" https://www.linkedin.com/in/harshith-mente-001492224?originalSubdomain=in">
           <div className='text-5xl flex transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-130 hover: duration-800'>
<AiFillLinkedin/>
        </div></a>
       
          <ul className='flex items-center'>
           
            <li><a className='bg-orange-500 text-white px-6 py-4 rounded-md ml-8' href="#">Resume</a></li>
          </ul> */}
          </nav>
          <motion.div
            id="Home"
            initial={{
              x: 500,
              opacity: 0,
              scale: 0.5,
            }}
            animate={{
              x: 0,
              opacity: 1,
              scale: 1,
            }}
            transition={{
              duration: 0.5,
            }}
            className=""
          >
            {/* relative bg-teal-500 rounded-full my-1 */}
            <Image
              className="mt-16 flex justify-center h-36 w-36  border-4 border-orange-500 rounded-full md:h-96 md:w-96 md:float-right md: py-8"
              src={avatar}
              alt={""}
            />
          </motion.div>

          <motion.div
            initial={{
              x: -500,
              opacity: 0,
              scale: 0.5,
            }}
            animate={{
              x: 0,
              opacity: 1,
              scale: 1,
            }}
            transition={{
              duration: 0.5,
            }}
            className="text-left "
          >
            <h1 className="text-3xl mt-36 font-russo font-normal md:text-6xl">
              Hi There!
            </h1>
            <h2 className="text-6xl  text-orange-500 font-russo font-semibold md:text-8xl">
              {" "}
              <Text />
            </h2>
            <h3 className="font-amatic text-4xl font-medium mt:4 md:mt-2 text-teal-200 md:text-7xl">
              Developer and an UI/UX Designer.
            </h3>
            <p className="mt-10 text-md text-gray-200 md:text-2xl">
              {" "}
              I'm an enthusiastic developer with a passion for creating
              innovative solutions and solving problems through code. As a
              beginner, I'm always eager to learn new technologies and expand my
              skillset.
            </p>
          </motion.div>
        </section>

        <section id="project" className="snap-center">
          <Skills />
        </section>
        <section id="skills" className="snap-start">
          <h1 className="text-4xl md:py-8 font-russo font-normal text-orange-500 md:text-6xl">
            Skills
          </h1>
          <div className="grid grid-cols-4">
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
            <SkillsImages directionLeft={false} />
          </div>
        </section>
        <section>
          <div id="Education" className="">
            <h3 className="text-4xl font-russo font-normal pt-8 mb-8 text-orange-500 md:text-6xl">
              Education
            </h3>

            <ol className="relative border-l border-gray-200 dark:border-gray-700">
              <li className="mb-10 ml-4">
                <div className=" absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className=" font-normal leading-none text-gray-400 dark:text-gray-300 md:text-lg">
                  2021 - 2026
                </time>
                <h3 className=" md:text-xl mt-1 font-semibold text-gray-900 dark:text-white">
                  Atal Bihari Vajpayee Indian Institute of Information
                  Technology and Management, Gwalior
                </h3>
                <p className="text-sm mb-4 md:text-base font-normal text-gray-900 dark:text-gray-300">
                  Integrated Post Graduate Masters of Technology, Information
                  Technology: CGPA - 8.29
                </p>
              </li>
              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 md:text-lg font-normal leading-none text-gray-300 dark:text-gray-300">
                  2019 - 2021{" "}
                </time>
                <h3 className="mt-1 md:text-xl font-semibold text-gray-900 dark:text-white">
                  Narayana Junior College
                </h3>
                <p className=" text-sm md:text-base font-normal text-gray-500 dark:text-gray-300">
                  Central Board of Secondary Education, <br></br>Grade XII: 95%{" "}
                </p>
              </li>
              <li className="ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 md:text-lg font-normal leading-none text-gray-300 dark:text-gray-300">
                  2007 - 2019
                </time>
                <h3 className="mt-1 md:text-xl font-semibold text-gray-900 dark:text-white">
                  {" "}
                  The Presidential School
                </h3>
                <p className=" text-sm md:text-base font-normal text-gray-500 dark:text-gray-300">
                  Central Board of Secondary Education, <br></br>Grade X: 97%{" "}
                </p>
              </li>
            </ol>
            <h3
              id="Achievements
"
              className="text-4xl font-russo font-normal mb-8 mt-24 text-orange-500 md:text-6xl"
            >
              Achievements
            </h3>

            <ul className=" text-sm md:text-lg mb-8 space-y-4 text-left text-gray-500 dark:text-gray-300">
              <li className="flex items-center space-x-3">
                <img
                  src="https://png.pngtree.com/png-vector/20190411/ourmid/pngtree-vector-trophy-icon-png-image_924782.jpg"
                  className="w-8 h-8 rounded-full"
                />
                <span>
                  Stood amongst the top 1 percentile in JEE Mains out of 10
                  Lakh+ Applicants.{" "}
                </span>
              </li>
              <li className="flex items-center space-x-3">
                <img
                  src="https://png.pngtree.com/png-vector/20190411/ourmid/pngtree-vector-trophy-icon-png-image_924782.jpg"
                  className="w-8 h-8 rounded-full"
                />
                <span>
                  Winner in the Mobile Designing category of AASF's UI / UX
                  Designing Contest, Aakriti conducted during my freshman year.
                </span>
              </li>
              <li className="flex items-center space-x-3">
                <img
                  src="https://png.pngtree.com/png-vector/20190411/ourmid/pngtree-vector-trophy-icon-png-image_924782.jpg"
                  className="w-8 h-8 rounded-full"
                />
                <span>
                  Batch Representative: AASF, The Techno - Managerial Forum of
                  the Institute
                </span>
              </li>
            </ul>
          </div>
        </section>
      </main>
      <footer className="p-4  bg-white min-w-full rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
        <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">
          © 2023{" "}
          
            Harshith Mente™
          
          . <br></br>
        </span>
   
      </footer>
    </div>
  );
}
